module.exports = {
Deck : [
    { id: 0, name: 'Skull King', value: 0, type: 'Skull King', valid: true},
    { id: 1, name: 'Alyra', value: 0, type: 'Mermaid', valid: true},
    { id: 2, name: 'Sirena', value: 0, type: 'Mermaid', valid: true},
    { id: 3, name: 'Bahij the Bandit', value: 0, type: 'Pirate', valid: true},
    { id: 4, name: 'Harry the Giant', value: 0, type: 'Pirate', valid: true},
    { id: 5, name: 'Juanita Jade', value: 0, type: 'Pirate', valid: true},
    { id: 6, name: 'Rascal of Rotan', value: 0, type: 'Pirate', valid: true},
    { id: 7, name: 'Rosie de Laney', value: 0, type: 'Pirate', valid: true},
    { id: 8, name: 'Jolly Ranger (1)', value: 1, type: 'Jolly Ranger', valid: true},
    { id: 9, name: 'Jolly Ranger (2)', value: 2, type: 'Jolly Ranger', valid: true},
    { id: 10, name: 'Jolly Ranger (3)', value: 3, type: 'Jolly Ranger', valid: true},
    { id: 11, name: 'Jolly Ranger (4)', value: 4, type: 'Jolly Ranger', valid: true},
    { id: 12, name: 'Jolly Ranger (5)', value: 5, type: 'Jolly Ranger', valid: true},
    { id: 13, name: 'Jolly Ranger (6)', value: 6, type: 'Jolly Ranger', valid: true},
    { id: 14, name: 'Jolly Ranger (7)', value: 7, type: 'Jolly Ranger', valid: true},
    { id: 15, name: 'Jolly Ranger (8)', value: 8, type: 'Jolly Ranger', valid: true},
    { id: 16, name: 'Jolly Ranger (9)', value: 9, type: 'Jolly Ranger', valid: true},
    { id: 17, name: 'Jolly Ranger (10)', value: 10, type: 'Jolly Ranger', valid: true},
    { id: 18, name: 'Jolly Ranger (11)', value: 11, type: 'Jolly Ranger', valid: true},
    { id: 19, name: 'Jolly Ranger (12)', value: 12, type: 'Jolly Ranger', valid: true},
    { id: 20, name: 'Jolly Ranger (13)', value: 13, type: 'Jolly Ranger', valid: true},
    { id: 21, name: 'Jolly Ranger (14)', value: 14, type: 'Jolly Ranger', valid: true},
    { id: 22, name: 'Green Suit (1)', value: 1, type: 'Green Suit', valid: true},
    { id: 23, name: 'Green Suit (2)', value: 2, type: 'Green Suit', valid: true},
    { id: 24, name: 'Green Suit (3)', value: 3, type: 'Green Suit', valid: true},
    { id: 25, name: 'Green Suit (4)', value: 4, type: 'Green Suit', valid: true},
    { id: 26, name: 'Green Suit (5)', value: 5, type: 'Green Suit', valid: true},
    { id: 27, name: 'Green Suit (6)', value: 6, type: 'Green Suit', valid: true},
    { id: 28, name: 'Green Suit (7)', value: 7, type: 'Green Suit', valid: true},
    { id: 29, name: 'Green Suit (8)', value: 8, type: 'Green Suit', valid: true},
    { id: 30, name: 'Green Suit (9)', value: 9, type: 'Green Suit', valid: true},
    { id: 31, name: 'Green Suit (10)', value: 10, type: 'Green Suit', valid: true},
    { id: 32, name: 'Green Suit (11)', value: 11, type: 'Green Suit', valid: true},
    { id: 33, name: 'Green Suit (12)', value: 12, type: 'Green Suit', valid: true},
    { id: 34, name: 'Green Suit (13)', value: 13, type: 'Green Suit', valid: true},
    { id: 35, name: 'Green Suit (14)', value: 14, type: 'Green Suit', valid: true},
    { id: 36, name: 'Yellow Suit (1)', value: 1, type: 'Yellow Suit', valid: true},
    { id: 37, name: 'Yellow Suit (2)', value: 2, type: 'Yellow Suit', valid: true},
    { id: 38, name: 'Yellow Suit (3)', value: 3, type: 'Yellow Suit', valid: true},
    { id: 39, name: 'Yellow Suit (4)', value: 4, type: 'Yellow Suit', valid: true},
    { id: 40, name: 'Yellow Suit (5)', value: 5, type: 'Yellow Suit', valid: true},
    { id: 41, name: 'Yellow Suit (6)', value: 6, type: 'Yellow Suit', valid: true},
    { id: 42, name: 'Yellow Suit (7)', value: 7, type: 'Yellow Suit', valid: true},
    { id: 43, name: 'Yellow Suit (8)', value: 8, type: 'Yellow Suit', valid: true},
    { id: 44, name: 'Yellow Suit (9)', value: 9, type: 'Yellow Suit', valid: true},
    { id: 45, name: 'Yellow Suit (10)', value: 10, type: 'Yellow Suit', valid: true},
    { id: 46, name: 'Yellow Suit (11)', value: 11, type: 'Yellow Suit', valid: true},
    { id: 47, name: 'Yellow Suit (12)', value: 12, type: 'Yellow Suit', valid: true},
    { id: 48, name: 'Yellow Suit (13)', value: 13, type: 'Yellow Suit', valid: true},
    { id: 49, name: 'Yellow Suit (14)', value: 14, type: 'Yellow Suit', valid: true},
    { id: 50, name: 'Purple Suit (1)', value: 1, type: 'Purple Suit', valid: true},
    { id: 51, name: 'Purple Suit (2)', value: 2, type: 'Purple Suit', valid: true},
    { id: 52, name: 'Purple Suit (3)', value: 3, type: 'Purple Suit', valid: true},
    { id: 53, name: 'Purple Suit (4)', value: 4, type: 'Purple Suit', valid: true},
    { id: 54, name: 'Purple Suit (5)', value: 5, type: 'Purple Suit', valid: true},
    { id: 55, name: 'Purple Suit (6)', value: 6, type: 'Purple Suit', valid: true},
    { id: 56, name: 'Purple Suit (7)', value: 7, type: 'Purple Suit', valid: true},
    { id: 57, name: 'Purple Suit (8)', value: 8, type: 'Purple Suit', valid: true},
    { id: 58, name: 'Purple Suit (9)', value: 9, type: 'Purple Suit', valid: true},
    { id: 59, name: 'Purple Suit (10)', value: 10, type: 'Purple Suit', valid: true},
    { id: 60, name: 'Purple Suit (11)', value: 11, type: 'Purple Suit', valid: true},
    { id: 61, name: 'Purple Suit (12)', value: 12, type: 'Purple Suit', valid: true},
    { id: 62, name: 'Purple Suit (13)', value: 13, type: 'Purple Suit', valid: true},
    { id: 63, name: 'Purple Suit (14)', value: 14, type: 'Purple Suit', valid: true},
    { id: 64, name: 'Escape', value: 0, type: 'Escape', valid: true},
    { id: 65, name: 'Escape', value: 0, type: 'Escape', valid: true},
    { id: 66, name: 'Escape', value: 0, type: 'Escape', valid: true},
    { id: 67, name: 'Escape', value: 0, type: 'Escape', valid: true},
    { id: 68, name: 'Escape', value: 0, type: 'Escape', valid: true},
    { id: 69, name: 'Loot', value: 0, type: 'Loot', valid: true},
    { id: 70, name: 'Loot', value: 0, type: 'Loot', valid: true},
    { id: 71, name: 'Kraken', value: 0, type: 'Kraken', valid: true},
    { id: 72, name: 'Tigress', value: 0, type: 'Pirate', valid: true},
]

}